a = input("Digite algo: ")
print("Qual o tipo primitivo? ", type(a))
print("Só tem espaços? ", a.isspace())
print("É um número? ", a.isnumeric())
print("É alfabético? ", a.isalpha())
print("É alfanumérico? ", a.isalnum())
print("Estão em maiúsculas? ", a.isupper())
print("Estão em minúsculas? ", a.islower())
print("Está capitalizada? ", a.istitle())
